### ISSUE TITLE
Only allow 1 press of the invite button 

### ISSUE THREAD

**Issue by bfrey08** [bfrey08/eventAPP#3]
If I press the invite attendee button multiple times in a row, it will duplicate the invites by that many times

**Comment by greenje262** [comment]
So, just to confirm, if the form submit is pressed repeatedly, it submits the form multiple times? Typing this question out makes me feel very silly

**Comment by bfrey08** [comment]
Yes that is correct haha, is there a way to grey out and block the submit button once it has been pressed? I think I've done this in the past on the frontend but I don't recall fully.

**Comment by greenje262** [comment]
solved in recent frontend-edits pr
